<?php
$groupName =array();
$db = Mage::getSingleton('core/resource')->getConnection('core_read');
$sql = "SELECT * FROM bigmall_contactlistgroup WHERE cid=".$currentCustomerId;
//echo $sql; 
$result = $db->query($sql);
if ($result)
{
	//$i=0;
	while ($row = $result->fetch(PDO::FETCH_ASSOC))
	{
		//$groupName[$i]['id']=$row['id'];
		$groupName[$row['id']]=$row['name'];
		//$i++;
	}
}


$id = $this->getRequest()->getParam('id', false);

//echo $d = $this->getRequest()->getParam('tbl', false);

if(is_numeric($id))
{
	$buttonText = 'Update Contact';
	$mode = 'edit';
	
	$db = Mage::getSingleton('core/resource')->getConnection('core_read');
	$sql = "SELECT * FROM bigmall_contactlist WHERE id=".$id;
	//echo $sql; 
	$result = $db->query($sql);
	if ($result)
	{
		while ($row = $result->fetch(PDO::FETCH_ASSOC))
		{
			$name = $row['name'];
			$phone = $row['phone'];
			$contactlistgroup = $row['contactlistgroup'];
		}
	}
}
else
{
	$buttonText = 'Add Contact';
	$mode = 'add';
	$name = '';
	$phone = '';
	$contactlistgroup = '';
}
?>
<div class="page-title">
  <h1>Add Contact</h1>
</div>


<div class="InnerText">
<form name="frm_add_contact" action="<?php echo Mage::getUrl('*/*/formPostSms'); ?>" method="post">
	<?php echo $this->getBlockHtml('formkey')?>
	<input type="hidden" name="customer_id" value="<?php echo $currentCustomerId; ?>" />
	<input type="hidden" name="group_type" value="addcontact" />
	
	<?php if(is_numeric($id)) { ?>
	<input type="hidden" name="id" value="<?php echo $id; ?>" />
	<?php } ?>
	<input type="hidden" name="mode" value="<?php echo $mode; ?>" />
	
    <table width="100%" cellspacing="5" border="0">
      <tbody>
        <tr>
          <td width="25%" height="35px" class="text3">Contact Name :</td>
          <td width="75%" height="35px" class="text3" colspan="2"><input value="<?php echo $name; ?>" class="input-text" type="text" style="width:260px;" id="name" name="name">
            <span style="color:#F00"> *</span></td>
        </tr>
        <tr>
          <td valign="top" height="35px" class="text3">Contact Number:</td>
          <td height="35px" class="text3" colspan="2"><input value="<?php echo $phone; ?>" class="input-text" type="text" style="width:260px;" id="phone" name="phone">
            <span style="color:#F00"> *</span></td>
        </tr>
        <tr>
          <td valign="top" height="35px" class="text3">Contact Group:</td>
          <td height="35px" class="text3" colspan="2">
		  	<select style="width:265px; height:20px" id="contactlistgroup" name="contactlistgroup">
              <option value=""></option>
			  <?php foreach($groupName as $k=>$v) { 
			  $sel='';
			  if($contactlistgroup==$k)
			  $sel='selected="selected"';
			  ?>
			  	<option <?php echo $sel; ?> value="<?php echo $k; ?>"><?php echo $v; ?></option>
			  <?php } ?>
            </select>
            <span style="color:#F00"> *</span></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td colspan="2">
            <div style="float:left; margin-right:5px" id="Button">
              <div>
                <button class="button"><span><span><?php echo $buttonText; ?></span></span></button>
              </div>
            </div></td>
        </tr>
      </tbody>
    </table>
  </form>
</div>

<script type="text/javascript">
function delete_item(id,title,tbl){
	var r=confirm("Do you want to delete item :"+title);
	if (r==true)
	{
		var loc ='<?php echo Mage::getUrl('*/*/delete/'); ?>id/'+id+'/tbl/'+tbl;
		window.location =loc;
		//alert(loc);
	}
	else
	{
		return false;
	} 		
}
</script>

<div style="margin-top:20px;">
<table class="member-grid" width="100%" border="1" cellspacing="0" cellpadding="10">
  <tr>
    <th>Contact Name</th>
	<th>Phone</th>
	<th>Group</th>
    <th>Actions</th>
  </tr>
<?php 
if(is_numeric($currentCustomerId))
{
	$db = Mage::getSingleton('core/resource')->getConnection('core_read');
	$result = $db->query("SELECT *,bigmall_contactlist.id as id,bigmall_contactlist.name as name, bigmall_contactlistgroup.name as gname
	FROM bigmall_contactlist 
	INNER JOIN bigmall_contactlistgroup
	ON bigmall_contactlist.contactlistgroup=bigmall_contactlistgroup.id
	WHERE bigmall_contactlist.cid=".$currentCustomerId."");
	if ($result)
	{
		while ($row = $result->fetch(PDO::FETCH_ASSOC))
		{ 
		//print_r($row);
		?>
		  <tr>
			<td><?php echo $row['name'] ?></td>
			<td><?php echo $row['phone'] ?></td>
			<td><?php echo $row['gname'] ?></td>
			<td><a href="<?php echo Mage::getUrl('*/*/*/id/'.$row['id']); ?>">Edit</a> / <a onclick="delete_item('<?php echo $row['id'] ?>','<?php echo $row['name'] ?>','bigmall_contactlist');" href="#">Delete</a></td>
		  </tr>
		<?php 
		}
	}
}	
?>
</table>
</div>
