<div class="page-title">
  <h1>Product Order</h1>
</div>
<?php

$productId = $this->getRequest()->getParam('id', false);
if( is_numeric($productId) ) {
	$db = Mage::getSingleton('core/resource')->getConnection('core_read');
	$sql = "SELECT item_id,order_id,qty_ordered,price,qty_shipped FROM sales_flat_order_item WHERE product_id=".$productId;
	$result = $db->query($sql);
	if ($result)
	{ ?>
	
<table class="member-grid" width="100%" border="1" cellspacing="0" cellpadding="10">
  <tr>
    <th>Order Id</th>
    <th>Customer Name</th>
    <th>Qty</th>
    <th>Total</th>
    <th>Status</th>
	<th>Shipped</th>
	<th>Order Date</th>
  </tr>
	<?php			
		while ($row = $result->fetch(PDO::FETCH_ASSOC))
		{ 
			$itemId = $row['item_id'];
			
			$orderId = $row['order_id'];
			$qtyOrdered = round($row['qty_ordered']);
			
			$order = Mage::getModel('sales/order')->load($orderId);
			
			$item = $order->getItemById($itemId);
			$shipmentStatus = $item->getStatus();
			
			$price = $order->formatPrice($row['price']);
			$status = $order->getStatusLabel();
			
			//$payment = $order->getPayment();
			//$shipStatus = $payment->getOrder();
			//$shippingId = $order->getShippingAddress()->getId();
			//$address = Mage::getModel('sales/order_address')->load($shippingId);
			//echo date("M j, Y g:i a",strtotime($order->getCreatedAt())) 
			//$customerFirstName = $order->getCustomerFirstname(); //$address->getFirstname();
			//$customerLastName = $order->getCustomerLastname(); //$address->getLastname();
			/*foreach ($order->getAllItems() as $itemId => $item)
			{
			//echo $item->getName() ;
			}*/
		
		
		?>
		<tr>
			<td><a href="<?php echo $this->getUrl('customer/orderdetails/view/id/'.$orderId); ?>"><?php echo $order->getRealOrderId(); ?></a></td>
			<td><?php echo $order->getCustomerName(); //$customerFirstName.' '.$customerLastName ?></td>
			<td><?php echo $qtyOrdered ?></td>
			<td><?php echo $price ?></td>
			<td><?php echo $status ?></td>
			<td><?php echo $shipmentStatus; ?></td>
			<td><?php echo $order->getCreatedAtFormated('medium'); ?></td>
		</tr>
		<?php 
		} 
		?>
</table>		
<?php  
	} 
}
?>
<br />
<br />
<a href="javascript:history.back();">Go Back</a>