<?php
$db = Mage::getSingleton('core/resource')->getConnection('core_read');
$sql = "SELECT * FROM member_info WHERE customer_id=".$currentCustomerId;
$result = $db->query($sql);
if ($result)
{
	while ($row = $result->fetch(PDO::FETCH_ASSOC))
	{
		$credit = $row['credit'];
	}
}
?>
<style>
.ui-selectmenu-menu ui-selectmenu-open{ left: 200px !important; }
</style>

<link type="text/css" href="<?php echo $this->getSkinUrl('css/'); ?>jquery-ui-1.8.9.custom.css" rel="stylesheet">
<link type="text/css" href="<?php echo $this->getSkinUrl('css/'); ?>jquery.ui.selectmenu.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/ui/'); ?>jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/ui/'); ?>jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/ui/'); ?>jquery.ui.position.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/ui/'); ?>jquery.ui.selectmenu.js"></script>
<script type="text/javascript">	
		jQuery(function(){			
			jQuery('select.airportfrom').selectmenu({
			
				width: 20,
				menuWidth: 262,
				handleWidth: 0,
				maxHeight:200,
				format: addressFormatting,	
				positionOptions: {
					my: "right top",
					at: "left center",
					offset: "-4 10"
				},
				select: function(event, options) {
				
					 jQuery(this).parent().parent().find(".searchboxfrom").first().val(options.value);
					//jQuery(".searchboxfrom").val(options.value);
					jQuery("a.airportfrom").css("border","0");
					jQuery("input#phone").val(options.value);
				},
			});
	

			jQuery("a.airportfrom").css("border","0");
			jQuery('a.airportfrom').removeClass("ui-state-hover");
			jQuery("a.airportfrom").empty();
			jQuery("a.airportfrom").append('<img src="<?php echo $this->getSkinUrl('images/'); ?>contacts.png" alt="" title="" border="0" width="20" />');
			
		
			
		});		
		
		
		var addressFormatting = function(text){
			var newText = text;
			//array of find replaces
			var findreps = [
				{find:/^([^\-]+) \- /g, rep: '<span class="ui-selectmenu-item-header">$1</span>'},
				{find:/([^\|><]+) \| /g, rep: '<span class="ui-selectmenu-item-content">$1</span>'},
				{find:/([^\|><\(\)]+) (\()/g, rep: '<span class="ui-selectmenu-item-content">$1</span>$2'},
				{find:/([^\|><\(\)]+)$/g, rep: '<span class="ui-selectmenu-item-content">$1</span>'},
				{find:/(\([^\|><]+\))$/g, rep: '<span class="ui-selectmenu-item-footer">$1</span>'}
			];
			
			for(var i in findreps){
				newText = newText.replace(findreps[i].find, findreps[i].rep);
			}
			return newText;
		}		
		
	</script>
<div class="page-title">
  <h1>Send SMS</h1>
</div>
  
<script type="text/javascript">
function submitform()
{
	document.forms["addcat"].submit()
}

function validation()
{
	 
var phone = document.getElementById("phone").value;
var contactlistgroup = document.getElementById("contactlistgroup").value;
var message = document.getElementById("message").value;


str = "";
if(message==""){
	jQuery.prompt("Enter enter message",{ show:'slideDown' });
	str = "not";
	return false;
	}

if(str == "")
{
	submitform();
}
}


</script>
  <div style="width:662px; padding-left:20px;" class="Middle">
    <div style="float:right; margin-right:10px;"><strong style="color:#CC3300">SMS Credit: </strong><?php echo $credit ?></div>
  </div>
  
  <?php if($credit > 0 ) { ?>
  
  <div class="InnerText">
<form name="frm_add_contact" action="<?php echo Mage::getUrl('*/*/formPostSmsSend'); ?>" method="post">
	<?php echo $this->getBlockHtml('formkey')?>
	<input type="hidden" name="customer_id" value="<?php echo $currentCustomerId; ?>" />
      <table width="100%" cellspacing="5" border="0">
        <tbody>
          <tr>
            <td width="25%" height="35px" class="text3">Phone :</td>
            <td width="75%" height="35px" class="text3">
			<div style="float: left;">
                <input class="input-text" type="text" style="width:260px; height:20px" id="phone" name="phone" />
				<select name="airportfrom" id="airportfrom" style="width: 25px; display: none; " class="airportfrom" aria-disabled="false">
				<?php 
				$db = Mage::getSingleton('core/resource')->getConnection('core_read');
				$sql = "SELECT * FROM bigmall_contactlist WHERE cid=".$currentCustomerId;
				//echo $sql; 
				$result = $db->query($sql);
				if ($result)
				{
					while ($row = $result->fetch(PDO::FETCH_ASSOC))
					{ ?>
					  <optgroup label="<?php echo $row['name'];?>">
					  <option><?php echo $row['phone'];?></option>
					  </optgroup>
					<?php }
				}
				?>
				</select>
				</div></td>
          </tr>
          <tr>
            <td valign="top" height="35px" class="text3">Contact Group:</td>
            <td height="35px" class="text3">
			<?php 
			$db = Mage::getSingleton('core/resource')->getConnection('core_read');
			$sql = "SELECT * FROM bigmall_contactlistgroup WHERE cid=".$currentCustomerId;
			//echo $sql; 
			$result = $db->query($sql);
			if ($result)
			{
				while ($row = $result->fetch(PDO::FETCH_ASSOC))
				{ ?>
					<input type="checkbox" name="contactlistgroup[]"  value="<?php echo $row['id'] ?>" id="contactlistgroup"/>&nbsp;<?php echo $row['name'] ?>&nbsp;&nbsp;
				<?php 
				}
			}
			?>
            </td>
          </tr>
          
<script type="text/javascript">
jQuery(document).ready(function(){


	var length = jQuery("#message").val().length;
	jQuery('.counter').html( length + ' characters');
	// bind on key up event
	jQuery("#message").keyup(function(){
		var new_length = jQuery("#message").val().length;
		jQuery('.counter').html( new_length + ' characters');
	});


/**
 * Character Counter for inputs and text areas
 */

});
function goBack()
  {
  
  window.location = 'manage-sms.php';
  return false;
  }
</script>

          <tr>
            <td valign="top" height="35px" style="vertical-align:top" class="text3">Message:<br>
              <span style="font-size:10px">(140 characters for 1 SMS)</span> </td>
            <td height="35px" class="text3"><textarea style="width:260px; " id="message" rows="10" name="message"></textarea>
              <span style="color:#F00"> *</span><br>
              <span class="counter">0 characters</span> </td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td></td>
            <td>
              <div style="float:left; margin-right:5px" id="Button">
                <div>
				  <button onclick="return validation()" class="button"><span><span><?php echo 'Send'; ?></span></span></button>
                </div>
              </div>
			  <?php /*?><div style="float:left; margin-right:5px" id="Button">
                <div>
				  <button onclick="return validation()" class="button"><span><span><?php echo 'Back'; ?></span></span></button>
                </div>
              </div><?php */?></td>
          </tr>
        </tbody>
      </table>
    </form>
  </div>
  
  <?php } else { ?>
  <p>You do not have sufficient credits to send SMS. Please consult administrator for credits.<br />
You can also view <a href="<?php echo $this->getUrl('customer/sms/guideline'); ?>" style="color:#990000; text-decoration:underline">Topup Guidelines</a> for credit request.</p>
  
   <?php  } ?>