<div class="Center">
<div class="page-title">
  <h1>Top Up Credit Guideline</h1>
</div>
  <?php /*?><div style="width:662px; padding-left:20px;" class="Middle">
  
    <div style="float:right; margin-right:10px;"><strong style="color:#CC3300">SMS Credit: </strong>49</div>
  </div><?php */?>
  <div class="InnerText">
    <script type="text/javascript">
function submitform()
{
	document.forms["text"].submit()
}
</script>
    <div style="width:630px; margin-left:0px;" class="Text">
<script type="text/javascript">
function goBack()
  {
  window.history.back()
  }
</script>
      To top up credit, please bank in to us and fax or email the bank-in slip to 07-3888888 / billing@umall.my.<br>
      <br>
      Bank details:<br>
      Maybank<br>
      50728272 8272<br>
      Magicbox Sdn Bhd<br>
      <br>
      NOTE:<br>
      RM100 - 100 SMS credits<br>
      RM200 - 210 SMS credits<br>
      RM500 - 1,000 SMS credits<br type="_moz">
    </div>
    <div style="height:30px" class="LineEnd"></div>
    <div class="LineEnd"></div>
  </div>
  <div style="float:left; margin-right:5px" id="Button">
	<div>
	  <button onclick="goBack()" class="button"><span><span><?php echo 'Back'; ?></span></span></button>
	</div>
  </div>
  
</div>