<?php 
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$db = Mage::getSingleton('core/resource')->getConnection('core_read');
$result = $db->query("SELECT * FROM ads WHERE place='top-header'");
if ($result)
{
?>
<div class="new-products">

  <div class="page-title">
	 <h2 class="subtitle">Advertisement</h2>
  </div>

  <ul class="products-grid" style="padding:0; list-style-type:none;">
  <?php
  while ($row = $result->fetch(PDO::FETCH_ASSOC)) {
  ?>
    <li class="item" style="padding-left:5px;">
      <div class="product-border">
        <a target="_blank" class="product-image" href="<?php echo $row['link_url']; ?>"><img width="216" height="159" src="<?php echo $mediaUrl.$row['main_file_url']; ?>"></a>
      </div>
    </li>
  <?php } ?>
  </ul>
</div>
<?php } ?>