<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
  
 *
 * @category   design_blank
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="footer">
	<div class="col-footer">
    	<p class="legality"><?php echo $this->getCopyright() ?></p>
    </div>
    <div class="col-footer-2">
        <div class="indent-col-footer-2">
        	<div class="small-menu">
				<?php echo $this->getChildHtml('cms_footer_links') ?>
                <?php echo $this->getChildHtml('footer_links') ?>
                <div class="clear-block"></div>
            </div>
            <p class="store_switcher"><?php echo $this->getChildHtml('store_switcher') ?></p>
            <?php /*?>Like this design? Browse for <a rel="nofollow" href="http://www.templatemonster.com/magento-themes.php" title="Magento Templates" target="_blank">more Magento themes</a>!<?php */?>
        </div>
    </div>
        <div class="clear-block"></div>
</div>
<script type="text/javascript">Cufon.now();</script>