<?php 
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$db = Mage::getSingleton('core/resource')->getConnection('core_read');
$result = $db->query("SELECT * FROM ads WHERE place='under-mid-body' ORDER BY sort_order LIMIT 0,1");
if ($result)
{
  while ($row = $result->fetch(PDO::FETCH_ASSOC)) {
  ?><div class="left"><a onclick="adsClick(<?php echo $row['ads_id']; ?>);" target="_blank" href="<?php echo $row['link_url']; ?>"><img width="750" height="115" src="<?php echo $mediaUrl.$row['main_file_url']; ?>"></a></div><?php 
	} 
} ?>