<?php

class ngg_Thumbnail {

    var $percent=100;
    /**
     * Maximum width of image during resize
     *
     * @var int
     * @access private
     */
    var $maxWidth = 216;
    /**
     * Maximum height of image during resize
     *
     * @var int
     * @access private
     */
    var $maxHeight = 159;
	
	/**
     * New dimensions of working image
     *
     * @var array
     */
    var $newDimensions = array();


    /**
     * Calculates new image width
     *
     * @param int $width
     * @param int $height
     * @return array
     */
    function calcWidth($width,$height) {
        $newWp = (100 * $this->maxWidth) / $width;
        $newHeight = ($height * $newWp) / 100;
        return array('newWidth'=>intval($this->maxWidth),'newHeight'=>intval($newHeight));
    }

    /**
     * Calculates new image height
     *
     * @param int $width
     * @param int $height
     * @return array
     */
    function calcHeight($width,$height) {
        $newHp = (100 * $this->maxHeight) / $height;
        $newWidth = ($width * $newHp) / 100;
        return array('newWidth'=>intval($newWidth),'newHeight'=>intval($this->maxHeight));
    }

    /**
     * Calculates new image size based on percentage
     *
     * @param int $width
     * @param int $height
     * @return array
     */
    function calcPercent($width,$height) {
        $newWidth = ($width * $this->percent) / 100;
        $newHeight = ($height * $this->percent) / 100;
        return array('newWidth'=>intval($newWidth),'newHeight'=>intval($newHeight));
    }

    /**
     * Calculates new image size based on width and height, while constraining to maxWidth and maxHeight
     *
     * @param int $width
     * @param int $height
     */
    function calcImageSize($width,$height) {
        $newSize = array('newWidth'=>$width,'newHeight'=>$height);

        if($this->maxWidth > 0) {

            $newSize = $this->calcWidth($width,$height);

            if($this->maxHeight > 0 && $newSize['newHeight'] > $this->maxHeight) {
                $newSize = $this->calcHeight($newSize['newWidth'],$newSize['newHeight']);
            }

            //$this->newDimensions = $newSize;
        }

        if($this->maxHeight > 0) {
            $newSize = $this->calcHeight($width,$height);

            if($this->maxWidth > 0 && $newSize['newWidth'] > $this->maxWidth) {
                $newSize = $this->calcWidth($newSize['newWidth'],$newSize['newHeight']);
            }

            //$this->newDimensions = $newSize;
        }

        $this->newDimensions = $newSize;
    }

    /**
     * Calculates new image size based percentage
     *
     * @param int $width
     * @param int $height
     */
    function calcImageSizePercent($width,$height) {
        if($this->percent > 0) {
            $this->newDimensions = $this->calcPercent($width,$height);
        }
    }

}

	$mediaCatUrl = Mage::getBaseUrl('media').'catalog/category/';
	
	$blankImg = $this->getSkinUrl('images/catalog/product/placeholder/');
	$root_category = Mage::getModel('catalog/category')->load(2);
	$subcategories = $root_category->getChildren();
	?>
<div class="new-products" style="width:738px; padding:0 6px;">
  <ul class="products-grid" style="padding:0; list-style-type:none;">
  <?php
  foreach(explode(',',$subcategories) as $subcategory) {
    if($subcategory==34) continue;
	$category = Mage::getModel('catalog/category')->load($subcategory);
  ?>
    <li class="item" style="padding-left:2px;">
      <div class="product-border">
        <h3 class="product-name"><a style="font-size:17px;" href="<?php echo $category->getUrl(); ?>"><?php echo $category->getName(); ?></a></h3>
        <a class="product-image" href="<?php echo $category->getUrl(); ?>">
		<?php 
		if( $category->getThumbnail()!='' ) {
			$img = $mediaCatUrl. $category->getThumbnail();
			list($width, $height, $type, $attr) = getimagesize($img);
			
			$obj = new ngg_Thumbnail();
			$obj->calcImageSize($width,$height);
			

			if(count($obj->newDimensions)>0)
			{
				$w = $obj->newDimensions[newWidth];
				$h = $obj->newDimensions[newHeight];
			} else {
				$w = 216;
				$h = 159;
			}
		}
		else
			$img =$blankImg.'online-shop.jpg';
		?>
		<img width="<?php echo $w ?>" height="<?php echo $h ?>" alt="<?php echo $category->getName(); ?>" src="<?php echo $img; ?>"></a>
      </div>
    </li>
  <?php } ?>
  </ul>
</div>
